trigger:
- main

parameters:
- name: inputDate
  type: string
  default: ''
  displayName: 'Input Date'
  

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: BuildJob
    displayName: Build Job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        echo "Input date is: $(inputDate)"
      displayName: 'Echo input date'
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'output'
